name = "careerplans-worker"
main = "src/index.ts"
compatibility_date = "2024-04-05"

# [vars]
# MY_VARIABLE = "my_value"

# [secrets]
# SECRET_KEY

# Development environment compatibility
[dev]
port = 8787

[[d1_databases]]
binding = "DB"
database_name = "careerplans-prod"
database_id = "332416e1-b5f2-4121-b987-cac025652acb"
